query {
  getAllTransactions {
    id
    type
    amount
    clearedDatetime
    cleared
    clearedAccountBalance
    account {
      id
      name
    }
    category {
      id
      name
    }
    payee {
      id
      name
    }
  }
}
